import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// In AI Studio, this file is usually generated by the set_up_firebase tool.
// If it's missing, we provide a placeholder to avoid build errors.
import firebaseConfig from '../../firebase-applet-config.json';

const app = initializeApp(firebaseConfig && Object.keys(firebaseConfig).length > 0 ? firebaseConfig : {
  apiKey: "placeholder",
  authDomain: "placeholder",
  projectId: "placeholder",
  storageBucket: "placeholder",
  messagingSenderId: "placeholder",
  appId: "placeholder"
});

// @ts-ignore
export const db = getFirestore(app, firebaseConfig?.firestoreDatabaseId);
export const auth = getAuth(app);
export const isFirebaseConfigured = firebaseConfig && Object.keys(firebaseConfig).length > 0;
